config/routes.rb
Rails.application.routes.draw do
  get 'options/new'

  get 'option/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "items#index"
  resources :categories
  resources :items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
  validates :name, presence: true
  validates_associated :option_groups
  validates_associated :options
  before_save :prepare_options_to_save
  before_update :prepare_options_to_save
  attr_accessor :raw_options

  def filter(attrs)
    # (" options -> '0144424b-d70b-4eed-a9fc-9008aecb37af' ->> 'value' = 'blue'
    # and options -> '326adcd0-8c1e-438a-bb52-5601d0e61073' ->> 'value' = 'medium' ")
    return items if attrs.blank?
    conditions = attrs.delete_if{|k, v| v.blank? or (v.is_a?(Hash) and (v['0'].blank? or v['1'].blank?)) }.map do |k, v|
      if v.is_a?(Hash) then
        "options -> '#{k}' ->> 'value' >= '#{v['0']}' and options -> '#{k}' ->> 'value' <= '#{v['1']}'"
      else
        "options -> '#{k}' ->> 'value' = '#{v}'"
      end
    end.join(' and ')
    items.where(conditions)
  end

  def option_groups
    @raw_options ||= read_attribute(:options).map{|index, opt|Option.new(opt)}
    groups = {}
    @raw_options.each do |option|
      groups[option.group_name] ||= Array.new
      groups[option.group_name] << option
    end
    @option_groups ||= groups.map do |name, options|
      g = OptionGroup.new(name: name)
      g.options = options
      g
    end
    @option_groups
  end

  def build_option_group(name = 'default')
    @option_groups ||= []
    grp = OptionGroup.new(name: name)
    grp.options = Option.new
    @option_groups << grp
    grp
  end

  def options
    option_groups.flat_map(&:options)
  end

  def option_groups_attributes=(attributes)
    @option_groups ||= []
    attributes.each do |index, attrs|
      next if '1' == attrs.delete("_destroy")
      @option_groups << OptionGroup.new(attrs)
    end
    # write_attribute(:options, prepare_options_to_save)
  end

  # private
    def prepare_options_to_save
      opts = {}
      generate_ids
      options.each do |option|
        option.validations['values'] = option.validations['values'].split(',').each{|item| item.strip!} if option.validations['values'].is_a?(String) and !option.validations['values'].blank?
        opts[option.id] = option
      end
      write_attribute(:options, opts)
    end

    def generate_ids
      options.each{|o| o.id = 0 if o.id.blank? }
      max = options.inject{|memo, o| memo.id > o.id ? memo : o }.id
      options.each do |o|
        if o.id.blank? or o.id == 0
          max = max + 1
          o.id = max
        end
      end
    end

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category
  delegate :options, to: :category, prefix: :category
  # delegate :option_groups, to: :category
  # delegate :option_groups_attributes=, to: :category
  attr_accessor :option_groups, :options
  before_save :prepare_options_to_save
  # after_initialize :options

  def option_groups
    groups = {}
    options.each do |option|
      groups[option.group_name] ||= Array.new
      groups[option.group_name] << option
    end
    @option_groups ||= groups.map do |name, options|
      g = OptionGroup.new(name: name)
      g.options = options
      g
    end
    @option_groups
  end

  def options
    options = category_options.map(&:dup)
    opts = read_attribute(:options)
    options.each{|o| opts.each{|k, v| o.value = v['value'] if k.to_i == o.id.to_i }}
    # write_attribute :options, options
  end

  def options_attributes=(attributes)
    options.each{|o| attributes.each{|k, v| o.value = v['value'] if v['id'].to_i == o.id.to_i }}
    # write_attribute(:options, options)
  end

  def prepare_options_to_save
    opts = {}
    options.each{ |o| opts[o.id] = { value: o.value } }
    write_attribute(:options, opts)
  end
end

app/models/option.rb
class Option
  include ActiveModel::Model
  attr_accessor :id, :name, :value, :group_name, :option_type, :validations
  validates :name, :group_name, presence: true


  def initialize(attr = nil)
    attr = ActiveSupport::HashWithIndifferentAccess.new(attr)
    @id = attr['id']
    @name = attr['name']
    @option_type = attr['option_type']
    @value = attr['value']
    @group_name = attr['group_name']
    @validations = attr['validations']
  end

  def persisted?() false; end
  def new_record?() false; end
  def marked_for_destruction?() false; end
  def _destroy() false; end

  # def attributes
  #   {name: @name, value: @value, group_name: @group_name}
  # end
end

app/models/option_group.rb
class OptionGroup
  include ActiveModel::Model
  attr_accessor :name, :options
  validates :name, presence: true

  def name=(value)
    @name = value
    options.each{|o| o.group_name = value } unless options.blank?
  end

  def options=(opts)
    if opts.respond_to? 'map'
      @options = opts.map {|opt| opt.group_name = name; opt}
    else
      opts.group_name = name
      @options = [opts]
    end
    @options
  end

  def build_option(attr = {})
    @options ||= []
    attr['group_name'] = name
    opt = Option.new(attr)
    options << opt
    opt
  end

  def options_attributes=(attributes)
    opts = []
    attributes.each do |index, attrs|
      next if '1' == attrs.delete("_destroy")
      attrs['id'] = SecureRandom.uuid if attrs['id'].blank?
      opts<< Option.new(attrs)
    end
    self.options = opts
  end

  def persisted?() false; end
  def new_record?() false; end
  def marked_for_destruction?() false; end
  def _destroy() false; end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end
  def show
    @category = Category.find params[:id]
    @filter = {}
    @filter = filter_params.to_h if params[:filter]
    @items = @category.filter(@filter)
  end
  def new
    @category = Category.new
    @category.build_option_group
  end
  def create
    @category = Category.new category_params
    if @category.save
      redirect_to @category
    else
      render 'new'
    end
  end
  def edit
    @category = Category.find params[:id]
  end

  def update
    @category = Category.find params[:id]
    if @category.update(category_params)
      redirect_to @category
    else
      render 'edit'
    end
  end

  public

    def filter_params
      params.require(:filter).permit!
    end

    def category_params
      params.require(:category).permit(:name, option_groups_attributes: [:name, :_destroy, options_attributes: [:id, :name, :option_type, :_destroy, validations: [:required, :values, :minimum, :maximum]]])
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end
  def show
    @item = Item.find params[:id]
  end
  def edit
    @item = Item.find params[:id]
    @category = @item.category
  end
  def update
    @item = Item.find params[:id]
    if @item.update(item_params)
      redirect_to @item
    else
      render 'edit'
    end
  end
  def new
    @category = Category.find(params[:category_id])
    @item = Item.new(category_id: @category.id)
  end
  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to @item
    else
      render 'new'
    end
    # render html: ("<pre>" + params.inspect + "</pre>").html_safe
  end

  public
    def item_params
      params.require(:item).permit(:id, :name, :category_id, options_attributes: [:id, :value])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_option(name, f, association)
    new_object = f.object.send("build_#{association.to_s.singularize}")
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize, f: builder)
    end
    link_to(name, '#', class: 'add_option', data:{id: id, fields: fields.gsub("\n", '')})
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/categories/_error.haml
- if obj.errors.any?
  .alert-error
    #{pluralize(obj.errors.count, 'error')}:
    %ul
      - obj.errors.full_messages.each do |msg|
        %li
          = msg

app/views/categories/_option.haml
%fieldset
  = render 'error', obj: f.object
  = f.hidden_field :id
  %p
    = f.label :name
    = f.text_field :name
  %p
    = f.label :option_type
    = f.select :option_type, %w(text_field select checkbox range datetime)
  %p
    Validations:
    = f.fields_for :validations, OpenStruct.new(f.object.validations) do |validation_form|
      %p
        = validation_form.label :required
        = validation_form.check_box :required
      %p
        = validation_form.label :values
        = validation_form.text_area :values, value: ->{ '' || validation_form.object.values.join(', ') if validation_form.object.values.is_a?(Array)}.call
      %p
        = validation_form.label :minimum
        = validation_form.text_field :minimum
      %p
        = validation_form.label :maximum
        = validation_form.text_field :maximum
  %p
    = f.hidden_field :_destroy
    = link_to 'Delete option', '#', class: 'option_field_remove'

app/views/categories/_option_group.haml
%fieldset
  = render 'error', obj: f.object
  %p
    = f.label :name
    = f.text_field :name
  %p
    = f.hidden_field :_destroy
    = link_to 'Delete option group', '#', class: 'option_field_remove'
  %h4
    Options:
  = f.fields_for :options do |option|
    = render 'option', f: option
  = link_to_add_option 'Add option', f, :options

app/views/categories/create.haml
%div
  = debug(params)

  = debug(@category)

%a
  = link_to "back", categories_path

app/views/categories/edit.haml
%a
  = link_to "back", categories_path
%h2
  Item
= render 'error', obj: @category
= form_for @category do |f|
  = f.label :name
  = f.text_field :name
  %h3
    Option groups:
  = f.fields_for :option_groups do |group|
    = render 'option_group', f: group
    %br
  = link_to_add_option 'Add option group', f, :option_groups
  %p
    = f.submit

app/views/categories/index.haml
%ul
  - @categories.each do |category|
    %li
      = link_to category.name, category_path(category)
%a
  = link_to "new category", new_category_path

app/views/categories/new.haml
%a
  = link_to "back", categories_path
%h2
  Category
= form_for @category do |f|
  = f.label :name
  = f.text_field :name

  %h3
    Option Groups:
  = f.fields_for :option_groups do |group|
    = render 'option_group', f: group
    %br
  = link_to_add_option 'Add option group', f, :option_groups
  %br
  = f.submit

= console

app/views/categories/option_partials/_range.haml
%p
  = option.name + ': '
  -#= range_field_tag "filter[#{option.id}]", @filter[option.id.to_s], in: option.validations[:minimum]..option.validations[:maximum], step: 1
  - min_value = @filter[option.id.to_s]['0'] if @filter[option.id.to_s]
  - max_value = @filter[option.id.to_s]['1'] if @filter[option.id.to_s]
  = text_field_tag "filter[#{option.id}][0]", min_value
  = text_field_tag "filter[#{option.id}][1]", max_value

app/views/categories/option_partials/_select.haml
%p
  = option.name + ': '
  = select_tag "filter[#{option.id}]", options_for_select(option.validations[:values], @filter[option.id.to_s]), include_blank: true

app/views/categories/option_partials/_text_field.haml
%p
  = option.name + ': '
  = text_field_tag "filter[#{option.id}]", @filter[option.id.to_s]

app/views/categories/show.haml
%h1
  = @category.name
= link_to 'Edit', edit_category_path(@category)
-#%h2
-#  Option groups:
-#-@category.option_groups.each do |group|
-#  Group name:
-#  = group.name
-#  %h3
-#    Options:
-#  - group.options.each do |option|
-#    %ol
-#      %p
-#        Name:
-#        = option.name
-#      %p
-#        Option type:
-#        = option.option_type
-#      %p
-#        Validations:
-#        = option.validations
-#    %br
-#= link_to 'back', categories_path

%h2
  Filter:

-#= form_for @category, method: :get do |f|
-#  = f.fields_for :option_groups do |group|
-#    = group.fields_for :options do |option|
-#      = render 'items/'+option.object.option_type, f: option
-#  = f.submit 'search', name: nil

= form_for @category, method: :get do |f|
  - @category.options.each do |option|
    = render "categories/option_partials/#{option.option_type}", option: option
  = f.submit :search, name: nil

- @filter.each do |k, v|
  %p
    = k + ': ' + v.to_s

%h2
  Items:

%ol
  - @items.each do |item|
    %li
      = item.name
      - item.options.each do |option|
        %p
          = option.name + ': ' + option.value.to_s

= console

app/views/categories/update.haml
%div
  = debug(params)

%a
  = link_to "back", categories_path
= console

app/views/items/_range.haml
%p
  = f.hidden_field :id
  = f.label f.object.name
  = f.range_field :value, min: f.object.validations[:minimum], max: f.object.validations[:maximum], step: 1

app/views/items/_select.haml
%p
  = f.hidden_field :id
  = f.label f.object.name
  = f.select :value, f.object.validations[:values]

app/views/items/_text_field.haml
%p
  = f.hidden_field :id
  = f.label f.object.name
  = f.text_field :value

app/views/items/create.haml
%div
  =debug(params)

  = debug(@item)

%a
  = link_to "back", items_path
= console

app/views/items/edit.haml
%a
  = link_to "back", item_path(@item)

%h1
  = @category.name
= form_for @item do |f|
  = f.hidden_field :category_id, value: @category.id
  = f.label :name
  = f.text_field :name
  %h2
    Options:
  - @item.option_groups.each do |group|
    %fieldset
      = "#{group.name}: "
      = f.fields_for :options, group.options do |option|
        = render option.object.option_type, f: option
  %br
  = f.submit

= console

app/views/items/index.haml
%p
  = form_tag new_item_path, method: :get do
    = select_tag :category_id, options_from_collection_for_select(Category.all, :id, :name)
    = submit_tag 'New item', name: nil

%ul
  - @items.each do |item|
    %li
      = link_to item.name, item_path(item)

-#%fieldset
-#  = form_tag items_path, method: :get do
-#    = select_tag :category_id, options_from_collection_for_select(Category.all, :id, :name)
-#    = submit_tag

app/views/items/new.haml
%a
  = link_to "back", items_path

%h1
  = @category.name
= form_for @item do |f|
  = f.hidden_field :category_id, value: @category.id
  = f.label :name
  = f.text_field :name
  %h2
    Options:
  - @item.option_groups.each do |group|
    %fieldset
      = "#{group.name}: "
      = f.fields_for :options, group.options do |option|
        = render option.object.option_type, f: option
  %br
  = f.submit

= console

app/views/items/show.haml
%h1
  = @item.name
= link_to "edit", edit_item_path(@item)
%h2
  Specifications:
- @item.option_groups.each do |group|
  %h3
    #{group.name}:
  - group.options.each do |option|
    %p
      #{option.name}:
      = option.value

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Delta</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to 'categories', categories_path %>
    <%= link_to 'items', items_path %>

    <%= yield %>
  </body>
</html>